### ISSUE TITLE
Can't find UpdateServer.bat

### ISSUE THREAD

**Issue by HYPExMon5ter** [PurityWasHere/Dead-Matter-Server-Installer#1]
Hello, I downloaded both RunMeFirst and UpdateServer and put them in a folder on my desktop named Dead Matter Server, ran RunMeFirst as admin and everything worked fine until I put in the path (same folder as the .bat files), then it said it couldn't find UpdateServer. Please help.

**Comment by PureIsntHere** [comment]
Its an issue with the way CMD handles spaces, I recommend using _ instead of spaces. That should clear it up for you
